openapi: 3.0.3
info:
  title: Authentication Server API
  description: Production-ready ASP.NET Core authentication microservice with JWT, refresh tokens, RBAC, and audit logging.
  version: 1.0.0
  contact:
    name: API Support

servers:
  - url: https://localhost:5001
    description: Local development

paths:
  /api/auth/register:
    post:
      tags: [Authentication]
      summary: Register a new user
      operationId: register
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '201':
          description: User registered successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthSuccessResponse'
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
        '409':
          description: Email already registered
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'

  /api/auth/login:
    post:
      tags: [Authentication]
      summary: Login with credentials
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthSuccessResponse'
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
        '429':
          description: Rate limited - too many failed attempts
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'

  /api/auth/logout:
    post:
      tags: [Authentication]
      summary: Logout and revoke refresh token
      operationId: logout
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Logout successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiSuccessResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'

  /api/auth/refresh:
    post:
      tags: [Authentication]
      summary: Refresh access token
      operationId: refreshToken
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshTokenRequest'
      responses:
        '200':
          description: Token refreshed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenRefreshResponse'
        '401':
          description: Invalid or expired refresh token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'

  /api/auth/verify:
    post:
      tags: [Authentication]
      summary: Verify access token validity
      operationId: verifyToken
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Token is valid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenVerifyResponse'
        '401':
          description: Invalid token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'

  /api/auth/password-reset:
    post:
      tags: [Authentication]
      summary: Request password reset
      operationId: requestPasswordReset
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PasswordResetRequest'
      responses:
        '200':
          description: Password reset initiated (always returns success to prevent email enumeration)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiSuccessResponse'

  /api/auth/password-reset/{token}:
    post:
      tags: [Authentication]
      summary: Reset password with token
      operationId: resetPassword
      parameters:
        - name: token
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PasswordResetConfirmRequest'
      responses:
        '200':
          description: Password reset successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiSuccessResponse'
        '400':
          description: Invalid or expired token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'

  /api/users/me:
    get:
      tags: [User Management]
      summary: Get current user profile
      operationId: getMyProfile
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Profile retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfileSuccessResponse'
        '401':
          description: Unauthorized
    put:
      tags: [User Management]
      summary: Update current user profile
      operationId: updateMyProfile
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateProfileRequest'
      responses:
        '200':
          description: Profile updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfileSuccessResponse'
        '400':
          description: Validation error
        '401':
          description: Unauthorized

  /api/users/change-password:
    post:
      tags: [User Management]
      summary: Change current user password
      operationId: changePassword
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangePasswordRequest'
      responses:
        '200':
          description: Password changed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiSuccessResponse'
        '400':
          description: Current password incorrect or validation error
        '401':
          description: Unauthorized

  /api/admin/users:
    get:
      tags: [Admin]
      summary: List all users (paginated)
      operationId: listUsers
      security:
        - bearerAuth: []
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: pageSize
          in: query
          schema:
            type: integer
            default: 20
      responses:
        '200':
          description: User list retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserListSuccessResponse'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - Admin role required

  /api/admin/users/{id}:
    get:
      tags: [Admin]
      summary: Get user details
      operationId: getUserById
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: User details retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDetailSuccessResponse'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: User not found

  /api/admin/users/{id}/roles:
    post:
      tags: [Admin]
      summary: Assign role to user
      operationId: assignRole
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AssignRoleRequest'
      responses:
        '200':
          description: Role assigned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiSuccessResponse'
        '400':
          description: Invalid role or already assigned
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: User or role not found

  /health:
    get:
      tags: [Health]
      summary: Liveness check
      operationId: healthCheck
      responses:
        '200':
          description: Service is alive

  /ready:
    get:
      tags: [Health]
      summary: Readiness check (includes database connectivity)
      operationId: readinessCheck
      responses:
        '200':
          description: Service is ready
        '503':
          description: Service not ready

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    RegisterRequest:
      type: object
      required: [email, password]
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          minLength: 8
        firstName:
          type: string
        lastName:
          type: string

    LoginRequest:
      type: object
      required: [email, password]
      properties:
        email:
          type: string
          format: email
        password:
          type: string

    RefreshTokenRequest:
      type: object
      required: [refreshToken]
      properties:
        refreshToken:
          type: string

    PasswordResetRequest:
      type: object
      required: [email]
      properties:
        email:
          type: string
          format: email

    PasswordResetConfirmRequest:
      type: object
      required: [newPassword]
      properties:
        newPassword:
          type: string
          minLength: 8

    UpdateProfileRequest:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string

    ChangePasswordRequest:
      type: object
      required: [currentPassword, newPassword]
      properties:
        currentPassword:
          type: string
        newPassword:
          type: string
          minLength: 8

    AssignRoleRequest:
      type: object
      required: [roleName]
      properties:
        roleName:
          type: string

    ApiSuccessResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        message:
          type: string
        timestamp:
          type: string
          format: date-time

    ApiErrorResponse:
      type: object
      properties:
        success:
          type: boolean
          example: false
        error:
          type: object
          properties:
            code:
              type: string
            message:
              type: string
            details:
              type: array
              items:
                type: string
        timestamp:
          type: string
          format: date-time

    UserProfile:
      type: object
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        isActive:
          type: boolean
        isVerified:
          type: boolean
        roles:
          type: array
          items:
            type: string
        createdAt:
          type: string
          format: date-time

    AuthSuccessResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        data:
          type: object
          properties:
            user:
              $ref: '#/components/schemas/UserProfile'
            accessToken:
              type: string
            refreshToken:
              type: string
        message:
          type: string
        timestamp:
          type: string
          format: date-time

    TokenRefreshResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        data:
          type: object
          properties:
            accessToken:
              type: string
            refreshToken:
              type: string
        message:
          type: string
        timestamp:
          type: string
          format: date-time

    TokenVerifyResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        data:
          type: object
          properties:
            valid:
              type: boolean
            user:
              $ref: '#/components/schemas/UserProfile'
        message:
          type: string
        timestamp:
          type: string
          format: date-time

    UserProfileSuccessResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        data:
          $ref: '#/components/schemas/UserProfile'
        message:
          type: string
        timestamp:
          type: string
          format: date-time

    UserListSuccessResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        data:
          type: object
          properties:
            items:
              type: array
              items:
                $ref: '#/components/schemas/UserProfile'
            totalCount:
              type: integer
            page:
              type: integer
            pageSize:
              type: integer
        message:
          type: string
        timestamp:
          type: string
          format: date-time

    UserDetailSuccessResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        data:
          type: object
          properties:
            id:
              type: string
              format: uuid
            email:
              type: string
            firstName:
              type: string
            lastName:
              type: string
            isActive:
              type: boolean
            isVerified:
              type: boolean
            roles:
              type: array
              items:
                type: string
            lastLoginAt:
              type: string
              format: date-time
            createdAt:
              type: string
              format: date-time
            updatedAt:
              type: string
              format: date-time
        message:
          type: string
        timestamp:
          type: string
          format: date-time
